var msg = [];
module.exports = msg;

msg.push("Thank you for taking a look at my application for the Discord Server Manager role at IOM.\n\nI thought the best way to show my knowledge of the platform would be to make a simple Discord bot to tell you more about me.\n\n**Enter `/start` to see this message.\n\nEnter `/next` to navigate the application.\n\nIf you get lost, Enter `/help` to see all available commands\n\n**\nThanks; I look forward to hearing from you!\n\n*N.B. If you're not familiar with Discord, this application uses commands to show you information about me. To use the commands, type a forward slash followed by the command name, e.g. `/next` (with no spaces) and press send.*");

msg.push("**About me**\n\nI'm a London-based musician, producer and DJ. Currently, I spend my time writing and performing music with The Long Faces, DJing and producing as Euchre, working at FOLD on the weekend, and teaching English part-time to school kids during the week. In my spare time I make basic scripts and programs, and make designs for the events and radio shows that I'm involved with.");

msg.push("**Identification of Music Group**\n\nI've been a member of IOM since 2017, when I first started going to dance events. Online communities like IOM have created a safe online space for people to connect over a common love for undergound music. Through this group I've discovered new music and met great people that I would've been unlikely to come across in everyday life.");

msg.push("**Why I'd like to work with IOM**\n\nIOM provides valuable insights into the trends of alternative culture, and using this community as a dataset to enable creatives to launch their careers and develop their audiences via BUMP Agency is a natural extension of the concept. The IOM group has a positive impact on alternative music culture on a global scale, and I'd love to be a part of the growth and development of this community through Discord.");

msg.push("**Developing IOM with Discord**\n\nDiscord's power and and flexibility makes it the perfect platform to manage teams and communities in the creative industries. Bots extend the power of Discord further still. A custom bot for the IOM Discord server would not only allow us to develop a custom user experience centred around music; it would also have the potential to automatically log which artists, tracks, labels and clubs are being talked about most. Here are some ideas that I have for the development of the server, in addition to the standard chat channels:\n\n• After joining the server, members select their pronouns and a role, and read the group rules before the other channels can be unlocked. (e.g. 'She/They, DJ' or 'He/Him, Listener')\n\n• An 'id-bot' processes id requests with the `/id` command:\n\n	- User fills out information like 'Location', 'DJ/artist' and 'Genre' if known\n\n	- The bot runs uploaded video through the Shazam API for a match\n\n	- If no match is found, it uses the genre information given to create a new thread in the relevant channel. (e.g. 'Techno', 'Experimental' or 'General')\n\n	- These threads are closed after a period of inactivity, and can be easily viewed by users who want to give track IDs.\n\n	- Separation of genres within different channels allows people to filter out music they don't like, avoiding common problems like techno heads complaining about 'too much tech house'.\n\n	- Successful track IDs would be labelled with 'Track' and 'Artist' tags. The tags for each track would then be added to a database which the agency can use to track current music and culture trends.\n\n• These are just some initial ideas; a proof of concept and dedicated JavaScript developer would likely be needed to make them a reality.");
